name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: Upload JS to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/better-jacuzzi-ui-card.js
          asset_name: better-jacuzzi-ui-card.js
          tag: ${{ github.ref }}
          overwrite: true

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: "plugin"
